import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";
// import { AuthProvider } from "./providers";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/spoutbreeze_icon.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>SpoutBreeze</title>
      </head>
      <body className={`${montserrat.className} flex flex-col min-h-screen mx-auto max-w-screen-container`}>
        <AppRouterCacheProvider>
          <nav>
            <Navbar />
          </nav>
          <main className="pt-[80px]">{children}</main>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
