name: Next.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
          
      - name: Debug environment file
        run: cat .env.local

      - name: Run ESLint (if ESLint is installed)
        run: npm run lint || echo "Skipping ESLint check"

      - name: Run TypeScript Check (if TypeScript is installed)
        run: npx tsc --noEmit || echo "Skipping TypeScript check"

      - name: Run Tests (if tests exist)
        run: npm test || echo "No tests found"

      - name: Build Project
        run: npm run build